# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 772afaa33a76850bafdd555df394793f3e787990180f12f529670bf9416fd5cc9d3a2cf673f6d8c4fb9d2d3c989663d5c66a0ff073d9c0907597240902ca01c6

test:
  secret_key_base: 062fd35e2c845f0106fff9ce2a019bcd39884e8178685e1d072b1aa1e7b83e34bde453211ef88188b136acff34b0acd6739405a3755fdc8fc37857ca2e15f7bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
